### ISSUE TITLE
add 1.3.4 fling sdk version

### ISSUE THREAD

**Issue by vikaschandra** [crelies/AmazonFling#1]
Please add latest version which has support for bitcode.

**Comment by crelies** [comment]
Thank you very much for the information. I published version 1.3.4 ;)

@vikaschandra I will release `FireTVKit` soon. Maybe you are interested ;) Take a look if you want.

**Comment by crelies** [comment]
@vikaschandra Version 1.3.4-rc.1 is released. It is ready to use.

I will release version 1.3.4 next month. There will be no difference to the release candidate. I can't release it right now because this repository is over its data quota (git lfs).

**Comment by crelies** [comment]
@vikaschandra I found a way. Version 1.3.4 is now available.

**Comment by vikaschandra** [comment]
I am still seeing the issue with update.It does not work.

[FlingError.txt](https://github.com/crelies/AmazonFling/files/2084341/FlingError.txt)

**Comment by crelies** [comment]
@vikaschandra You need to install git lfs because the Amazon Fling binary is too large for a normal git repository. Do this via homebrew using `brew install git-lfs`. For more information visit [Git LFS](https://git-lfs.github.com/).

**Comment by vikaschandra** [comment]
Thanks.Issue is fixed.
